### ISSUE TITLE
Error gramatical: harina en minúscula

### ISSUE THREAD

**Issue by teregithub** [pedrocursos/la-morada-del-pan#12]
En la receta de pan de espelta la palabra *Harina* tiene que ir en minúscula, pues forman parte de la frase.

**Comment by teregithub** [comment]
Si están de acuerdo, lo cambiaré.

**Comment by pedrocursos** [comment]
Ok, tienes razón. Por favor, cámbialo.

**Comment by teregithub** [comment]
Ok, me pongo a ello.

**Comment by pedrocursos** [comment]
Gracias @teregithub
