### ISSUE TITLE
Sustituir la levadura por masa madre en el pan de espelta

### ISSUE THREAD

**Issue by pedrocursos** [pedrocursos/la-morada-del-pan#3]
Reemplazar 50 gr. de levadura por 165 gr. de masa madre. Este cambio es recomendable por los beneficios que tiene la masa madre para la salud y el sabor del pan.

**Comment by teregithub** [comment]
Lo cambio.

**Comment by pedrocursos** [comment]
Gracias @teregithub

**Comment by josemagithub** [comment]
Ok, comprendido. Probaré la reducción de levadura en la masa madre.
