### ISSUE TITLE
¿Se puede reducir la cantidad de levadura en la masa madre?

### ISSUE THREAD

**Issue by pedrocursos** [pedrocursos/la-morada-del-pan#4]
Para que el pan sea más saludable y tenga mejor sabor, cuanta menor cantidad de levadura tenga mucho mejor. Entonces, habría que experimentar hasta saber qué mínima cantidad de levadura sería apropiada para la masa madre.

**Comment by josemagithub** [comment]
Empezaré a probar con la mitad que viene en la receta, es decir, 25 gr. Iré contando cuales son los resultados.

**Comment by josemagithub** [comment]
Ha salido muy bien el pan con 25 gr. de levadura. Volveré a probar con la mitad, o sea, 12,5 gr.

**Comment by pedrocursos** [comment]
¡Enhorabuena! Sigue con tu investigación y nos cuentas.

**Comment by josemagithub** [comment]
Ok, sigo.

**Comment by pedrocursos** [comment]
¡Vaya! @josemagithub Te pido disculpas, pero me equivoqué al aprobar este PR. Ha quedado modificado el pan de espelta otra vez con levadura, cuando tendría que ser masa madre. ¿Puedes cambiarlo? Sino, no te preocupes, y lo haré yo.

**Comment by josemagithub** [comment]
Ok, no te preocupes, a todos nos puede pasar. @pedrocursos

**Comment by pedrocursos** [comment]
Gracias @josemagithub por tu ayuda y comprensión.
